/*! ****************************************************************************
 * TaskQ v0.0.6
 *
 * A library that processes tasks sequentially.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2020 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from ES6Kadoo v0.0.0-beta.9.
 * ************************************************************************** */
/*! Generated by Kadoo v0.0.0-beta.6 */
const $__ES6GLOB={};!function(t,n){"use strict";"function"==typeof define&&define.amd?define([""],n):"object"==typeof exports?module.exports=n(t):t.TaskQ=n(t)}($__ES6GLOB,t=>{"use strict";let n={src:{taskq:{},private:{taskq:{}}},extend:function(t,n){for(var e=Object.keys(n),s=0;s<e.length;s++)t[e[s]]=n[e[s]]}};return function(){const e=n.src.private.taskq,s=t.TaskQ;let i;const r=function(){const t=Object.create(i);return t.library={name:"TaskQ",version:"0.0.6"},t._dQ={},t};r.VERSION="0.0.6",r._setTestMode=function(){return[]},r.noConflict=function(){return t.TaskQ=s,this},i={pushQ(t,n){return e.pushQ(this._dQ,t,n),this},popQ(t,n){return e.popQ(this._dQ,t,n),this}},n.src.taskq=r}(),function(){function t(t,n){"string"!=typeof n||Object.prototype.hasOwnProperty.call(t,n)||(t[n]={firing:!1,listeners:[]})}const e={pushQ(n,e,s){t(n,e),"string"==typeof e&&"function"==typeof s&&(n[e].listeners.push(s),n[e].firing||function(t,n,e){const s=t[n].listeners;t[n].firing=!0,function i(){s.length>0?s.shift().apply(e||{},[i].concat(Array.prototype.slice.call(arguments,0))):t[n].firing=!1}()}(n,e))},popQ(n,e,s){t(n,e),"string"==typeof e&&"function"==typeof s&&(n[e].listeners.push(s),n[e].firing||function(t,n,e){const s=t[n].listeners;t[n].firing=!0,function i(){if(s.length>0){for(;s.length>1;)s.shift();s.shift().apply(e||{},[i].concat(Array.prototype.slice.call(arguments,0)))}else t[n].firing=!1}()}(n,e))}};n.extend(n.src.private.taskq,e)}(),n.src.taskq});export default $__ES6GLOB.TaskQ;